# Generated by Django 4.0.3 on 2022-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('GROUP', 'GROUP')], default='PRIVATE', max_length=48),
        ),
    ]
